# Generated by Django 4.2.7 on 2023-12-27 21:50

import administrator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="logo_path",
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.ImageField(upload_to=administrator.models.logo)),
                ("state", models.CharField(default="Activa", max_length=240)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
                "ordering": ["created"],
            },
        ),
    ]
