# Generated by Django 4.2.7 on 2023-12-27 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0002_remove_config_logo_path_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logo",
            name="config",
        ),
    ]
