# Generated by Django 5.0.3 on 2024-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_name', models.CharField(blank=True, default='N/A', max_length=240, null=True, verbose_name='Manual')),
                ('manual_path', models.CharField(blank=True, default='N/A', max_length=240, null=True, verbose_name='Ubicación')),
                ('manual_description', models.TextField(blank=True, default='N/A', max_length=240, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuales',
                'ordering': ['manual_name'],
            },
        ),
    ]
