# Generated by Django 4.2.7 on 2024-01-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
        ("incident", "0002_incident_deparment"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="management",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.management",
            ),
        ),
    ]
