# Generated by Django 4.2.7 on 2023-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fields",
            name="kind_field",
            field=models.CharField(
                blank=True,
                default="standard",
                max_length=240,
                null=True,
                verbose_name="Tipo_campo",
            ),
        ),
    ]
