# Generated by Django 4.2.7 on 2023-12-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("department", "0001_initial"),
        ("poll", "0002_fields_kind_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_name",
                    models.CharField(
                        blank=True,
                        default="N/A",
                        max_length=240,
                        null=True,
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha solicitud"
                    ),
                ),
                (
                    "request_delivery",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha derivación"
                    ),
                ),
                (
                    "request_accept",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha aceptación"
                    ),
                ),
                (
                    "request_close",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha cierre"
                    ),
                ),
                (
                    "request_state",
                    models.CharField(
                        blank=True,
                        default="Iniciada",
                        max_length=100,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "deparment",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.deparment",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "ordering": ["request_date"],
            },
        ),
        migrations.CreateModel(
            name="RequestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_record_kind",
                    models.CharField(
                        blank=True,
                        default="N/A",
                        max_length=240,
                        null=True,
                        verbose_name="Tipo de registro",
                    ),
                ),
                (
                    "request_record_text",
                    models.CharField(
                        blank=True,
                        default="N/A",
                        max_length=240,
                        null=True,
                        verbose_name="Registro",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro solicitud",
                "verbose_name_plural": "Registros solicitudes",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="RequestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_answer_text",
                    models.CharField(
                        blank=True,
                        default="N/A",
                        max_length=240,
                        null=True,
                        verbose_name="Tipo de registro",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "fields",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.fields",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "ordering": ["created"],
            },
        ),
    ]
