# Generated by Django 4.2.7 on 2024-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0002_deparment_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="deparment",
            name="deparment_in_charge",
            field=models.CharField(
                blank=True,
                default="N/A",
                max_length=240,
                null=True,
                verbose_name="Encargado",
            ),
        ),
        migrations.AddField(
            model_name="deparment",
            name="deparment_in_charge_mail",
            field=models.CharField(
                blank=True,
                default="N/A",
                max_length=240,
                null=True,
                verbose_name="Encargado Correo",
            ),
        ),
    ]
